name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
      - '!vscode-v*'

permissions:
  contents: read

jobs:
  build:
    name: Build distribution
    strategy:
      matrix:
        include:
          - os: linux
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - os: linux
            target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
          - os: macos
            target: aarch64-apple-darwin
            runner: macos-14
          - os: windows
            target: x86_64-pc-windows-msvc
            runner: windows-latest
    
    runs-on: ${{ matrix.runner }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        args: --release --out dist --find-interpreter
        sccache: 'true'
        manylinux: auto
    
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.target }}
        path: dist

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/project/t-linter/
    permissions:
      id-token: write
    
    steps:
    - name: Download all wheels
      uses: actions/download-artifact@v4
      with:
        pattern: wheels-*
        path: dist
        merge-multiple: true
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
